---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: ssb-server
  name: ssb-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ssb-server
  template:
    metadata:
      labels:
        app: ssb-server
    spec:
      containers:
      - name: ssb-server
        envFrom:
        - configMapRef:
            name: ssb-server
        image: distributedmind/ssb-server:latest

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ssb-server
  name: ssb-server
spec:
  ports:
  - name: ssb-server
    port: 8008
    targetPort: 8008
  selector:
    app: ssb-server
  type: ClusterIP